[phases.setup]
nixPkgs = ["nodejs-20_x", "python3", "sqlite", "nodePackages.node-gyp", "gcc", "make"]

[phases.install]
cmds = [
  "npm install --verbose",
  "npm rebuild better-sqlite3"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"

